server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techsupp
    username: techsupp
    password: techsuppkitri
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      # create, create-drop, update, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


#profiles: naver
#security:
#  oauth2:
#    client:
#      registration:
#        naver:
#          client-name: naver
#          client-id: [발급받은 client id]
#          client-secret: [발급받은 client secret]
#          redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
#          authorization-grant-type: authorization_code
#          scope:
#            - email
#            - name
#            - profile_image
#      provider:
#        naver:
#          authorization-uri: https://nid.naver.com/oauth2.0/authorize
#          user-info-uri: https://openapi.naver.com/v1/nid/me
#          token-uri: https://nid.naver.com/oauth2.0/token
#          user-name-attribute: response

